name: derry
description: A script manager to help you define script shortcuts and use them effortlessly, and performantly.
version: 1.3.0
repository: https://github.com/frencojobs/derry

environment:
  sdk: ">=2.10.0 <3.0.0"

executables:
  derry:

dependencies:
  args: ^2.1.0
  console: ^4.1.0
  equatable: ^2.0.2
  ffi: ^1.0.0
  path: ^1.7.0
  string_similarity: ^2.0.0
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^2.0.3
  build_version: ^2.0.1
  lint: ^1.3.0
  test: ^1.6.0

scripts: derry.yaml
